CALCULUS_CONCEPTS = {
    "Product Rule": {
        "core_idea": "The Product Rule is our special recipe for finding the derivative of a function that is the *product* of two other functions. You can't just multiply their individual derivatives—that's a classic rookie mistake! The rule says if $h(x) = f(x)g(x)$, then the derivative is $h'(x) = f'(x)g(x) + f(x)g'(x)$. Think of it as a dance: 'derivative of the first times the second, plus the first times the derivative of the second.'",
        "real_world_application": "Imagine you run a business where both the number of items you sell, $N(t)$, and the price per item, $P(t)$, are changing over time (maybe due to seasonal demand and inflation). Your total revenue is $R(t) = N(t)P(t)$. To find out how fast your revenue is changing at any moment, you need the Product Rule! It tells you how the change in sales and the change in price *combine* to affect your total revenue.",
        "mathematical_demonstration": "Let's find the derivative of $h(x) = x^2 \sin(x)$. Here, our two functions are $f(x) = x^2$ and $g(x) = \sin(x)$.<br>1. Find the derivatives of the parts: $f'(x) = 2x$ and $g'(x) = \cos(x)$.<br>2. Apply the Product Rule formula: $h'(x) = f'(x)g(x) + f(x)g'(x)$.<br>3. Substitute everything in: $h'(x) = (2x)(\sin(x)) + (x^2)(\cos(x))$.<br>And that's our answer: $2x\sin(x) + x^2\cos(x)$. We've successfully found the rate of change for a complex function!",
        "explanation": "The Product Rule is a fundamental differentiation rule used when a function is composed of the product of two differentiable functions."
    },
    "Chain Rule": {
        "core_idea": "The Chain Rule is the master key for nested functions, or 'functions within a function,' like $\sin(x^2)$. It's like a Russian nesting doll of math! The rule says if you have $h(x) = f(g(x))$, its derivative is $h'(x) = f'(g(x)) \cdot g'(x)$. In simple terms: 'take the derivative of the outside function (leaving the inside alone), then multiply by the derivative of the inside function.'",
        "real_world_application": "A weather balloon is rising, and as it rises, the temperature drops. The balloon's altitude is a function of time, $A(t)$, and the temperature is a function of altitude, $T(A)$. To find how fast the temperature is changing *with respect to time*, you need to find $\\frac{dT}{dt}$. The Chain Rule connects these rates: $\\frac{dT}{dt} = \\frac{dT}{dA} \cdot \\frac{dA}{dt}$. It 'chains' the rates together!",
        "mathematical_demonstration": "Let's find the derivative of $h(x) = (x^3 + 5)^4$. The 'outside' function is $f(u) = u^4$ and the 'inside' is $g(x) = x^3 + 5$.<br>1. Derivative of the outside: $f'(u) = 4u^3$.<br>2. Derivative of the inside: $g'(x) = 3x^2$.<br>3. Apply the Chain Rule: $h'(x) = f'(g(x)) \cdot g'(x)$.<br>4. Substitute: $h'(x) = 4(x^3 + 5)^3 \cdot (3x^2)$.<br>Clean it up: $h'(x) = 12x^2(x^3 + 5)^3$. You just tamed a gnarly nested function!",
        "explanation": "The Chain Rule is used to find the derivative of composite functions."
    }
}