INTEGRATION_CONCEPTS = {
    "U-Substitution": {
        "core_idea": "U-Substitution is the Chain Rule in reverse! It's our go-to technique for integrals that have a nested function and its derivative hanging around. We simplify the integral by defining a new variable, 'u', for the 'inside' part. The goal is to transform a complicated integral in terms of $x$ into a much simpler one in terms of $u$. It's like changing the language of the problem to one you can actually speak.",
        "real_world_application": "Imagine calculating the total energy consumed by a device whose power usage, $P(t)$, follows a complex pattern, like $P(t) = (2t+1)^3$. To find the total energy (the integral of power), a U-substitution where $u = 2t+1$ would make the problem vastly simpler to solve, turning a messy integral into a basic power rule problem.",
        "mathematical_demonstration": "Let's solve $\int 2x \cos(x^2) dx$. This looks tough! But notice the 'inside' function $x^2$ and its derivative $2x$ are both present.<br>1. Let $u = x^2$. This is our substitution.<br>2. Find the derivative of u: $\\frac{du}{dx} = 2x$. Rearrange this to solve for $dx$: $du = 2x dx$.<br>3. Now substitute *everything* into the original integral. The $\cos(x^2)$ becomes $\cos(u)$, and the $2x dx$ becomes $du$.<br>Our integral is now just $\int \cos(u) du$. That's easy! The integral is $\sin(u) + C$.<br>4. Finally, substitute back to $x$: $\sin(x^2) + C$. We did it!",
        "explanation": "U-Substitution is a method for finding integrals by reversing the chain rule of differentiation."
    },
    "Integration by Parts": {
        "core_idea": "Integration by Parts is the Product Rule in reverse. It's for integrating a function that looks like a product of two other functions. The formula is $\int u dv = uv - \int v du$. The secret is choosing your 'u' and 'dv' wisely. A good acronym is LIATE (Logarithmic, Inverse Trig, Algebraic, Trig, Exponential) - pick your 'u' based on what comes first in that list. It often turns one impossible integral into a much easier one.",
        "real_world_application": "In signal processing, to find the average value of a signal that is the product of two functions (like an exponentially decaying sine wave, $e^{-t}\sin(t)$), Integration by Parts is essential. It helps break down the complex signal into parts that can be analyzed.",
        "mathematical_demonstration": "Let's solve $\int x \cos(x) dx$. This is a product.<br>1. Choose u and dv using LIATE. 'x' is Algebraic, 'cos(x)' is Trig. A comes before T, so we pick $u = x$ and $dv = \cos(x) dx$.<br>2. Find du and v. If $u=x$, then $du = dx$. If $dv = \cos(x) dx$, we integrate to get $v = \sin(x)$.<br>3. Plug into the formula $\int u dv = uv - \int v du$:<br>$\int x \cos(x) dx = x\sin(x) - \int \sin(x) dx$.<br>4. Solve the new, easier integral: $\int \sin(x) dx = -\cos(x)$.<br>5. Combine everything: $x\sin(x) - (-\cos(x)) + C = x\sin(x) + \cos(x) + C$. Voilà!",
        "explanation": "Integration by Parts is a technique for integrating the product of two functions."
    }
}