TRIGONOMETRY_CONCEPTS = {
    "Pythagorean Identity": {
        "core_idea": "The Pythagorean Identity, $\sin^2\theta + \cos^2\theta = 1$, is the most important equation in all of trigonometry. It comes directly from the unit circle and the Pythagorean Theorem ($a^2+b^2=c^2$). On the unit circle, the coordinates are $(\cos\theta, \sin\theta)$ and the radius (hypotenuse) is 1. So, $x^2+y^2=r^2$ becomes $\cos^2\theta + \sin^2\theta = 1^2$. It means that for *any* angle, if you know its sine, you can find its cosine, and vice-versa.",
        "real_world_application": "In robotics, if a robotic arm of length 1 is controlled by an angle $\theta$, its endpoint has coordinates $(\cos\theta, \sin\theta)$. This identity provides a constant check on the validity of the arm's position. It's also fundamental in computer graphics for creating realistic lighting and reflection models, ensuring that calculations involving angles and distances remain consistent.",
        "mathematical_demonstration": "Suppose you know that for a certain angle $\theta$ in the first quadrant, $\sin\theta = \frac{3}{5}$. What is $\cos\theta$?<br>1. Start with the identity: $\sin^2\theta + \cos^2\theta = 1$.<br>2. Plug in the known value: $(\frac{3}{5})^2 + \cos^2\theta = 1$.<br>3. Simplify: $\frac{9}{25} + \cos^2\theta = 1$.<br>4. Solve for $\cos^2\theta$: $\cos^2\theta = 1 - \frac{9}{25} = \frac{16}{25}$.<br>5. Take the square root: $\cos\theta = \pm\sqrt{\frac{16}{25}} = \pm\frac{4}{5}$.<br>Since we are in the first quadrant, cosine is positive, so $\cos\theta = \frac{4}{5}$. You found one trig value from another without even knowing the angle!",
        "explanation": "The Pythagorean Identity is a fundamental relation in trigonometry that states that for any angle, the square of the sine plus the square of the cosine is 1."
    },
    "Law of Sines": {
        "core_idea": "The Law of Sines is a powerful tool for solving triangles that are *not* right-angled. It creates a beautiful ratio between the sides of a triangle and the sines of their opposite angles: $\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}$. If you know two angles and one side (AAS or ASA), or two sides and a non-included angle (SSA), you can use this law to find all the missing parts of the triangle.",
        "real_world_application": "Surveyors use this all the time! Imagine you need to find the distance to a faraway mountain peak. You can't measure it directly. So, you create a baseline between two points (A and B) and measure the distance. From each point, you measure the angle to the peak (C). Now you have a triangle where you know one side (the baseline) and two angles. The Law of Sines lets you calculate the other two sides—the distances to the peak!",
        "mathematical_demonstration": "Consider a triangle with angle $A=30^\circ$, angle $B=70^\circ$, and side $a=8$. Let's find the length of side $b$.<br>1. First, find angle C: $C = 180^\circ - 30^\circ - 70^\circ = 80^\circ$.<br>2. Set up the Law of Sines: $\frac{a}{\sin A} = \frac{b}{\sin B}$.<br>3. Plug in the known values: $\frac{8}{\sin 30^\circ} = \frac{b}{\sin 70^\circ}$.<br>4. Solve for b: $b = \frac{8 \cdot \sin 70^\circ}{\sin 30^\circ}$.<br>5. Calculate: $\sin 70^\circ \approx 0.940$ and $\sin 30^\circ = 0.5$. So, $b \approx \frac{8 \cdot 0.940}{0.5} = 15.04$. You've just found the length of a side without ever measuring it directly!",
        "explanation": "The Law of Sines relates the lengths of the sides of a triangle to the sines of its angles."
    }
}